### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by Nesh108** [grebtsew/Bomberman#1]
Hello!

I like this fun project and I would like to know whether I can fork it and modify it (for non-commercial use).
Would it be possible for you to add a license for this?

Thanks :)

**Comment by grebtsew** [comment]
Hi @Nesh108,

Thanks for checking out the project! I updated the project with a License in main branch.

I close this issue, as it is hopefully solved now. Let me know if you have any questions.
